



#include "stdafx.h"
#include "OlympCoreDist.h"
#include "anova_tworep_dist.h"

using namespace Descriptive;

TCErrorCode stats_infer_anova_two_way_rep_compute_f_e_dist(const TCDistArray* data,
    TCUInt64  cnt_row_sample,
    TCFloat   alpha,
    TCFloat*  f_sample,
    TCFloat*  f_col,
    TCFloat*  f_int,
    TCFloat*  p_sample,
    TCFloat*  p_col,
    TCFloat*  p_int,
    TCFloat*  f_crit_sample,
    TCFloat*  f_crit_col,
    TCFloat*  f_crit_int,
    TCFloat*  ss_sample,
    TCFloat*  ss_col,
    TCFloat*  ss_int,
    TCFloat*  ss_err,
    TCFloat*  ss_tot,
    TCUInt64* df_sample,
    TCUInt64* df_col,
    TCUInt64* df_int,
    TCUInt64* df_err,
    TCUInt64* df_tot,
    TCFloat*  ms_sample,
    TCFloat*  ms_col,
    TCFloat*  ms_int,
    TCFloat*  ms_err,
    TCDistArray* s_cnt_sample,
    TCDistArray* s_sum_sample,
    TCDistArray* s_avg_sample,
    TCDistArray* s_var_sample,
    TCDistArray* s_cnt_col,
    TCDistArray* s_sum_col,
    TCDistArray* s_avg_col,
    TCDistArray* s_var_col,
    TCDistArray* s_cnt_col_sample,
    TCDistArray* s_sum_col_sample,
    TCDistArray* s_avg_col_sample,
    TCDistArray* s_var_col_sample)
{
    return stats_infer_anova_tworep_dist<TCFloat>(data, cnt_row_sample, alpha,
                                            f_sample, f_col, f_int,
                                            p_sample, p_col, p_int,
                                            f_crit_sample, f_crit_col, f_crit_int,
                                            ss_sample, ss_col, ss_int, ss_err, ss_tot,
                                            df_sample, df_col, df_int, df_err, df_tot,
                                            ms_sample, ms_col, ms_int, ms_err,
                                            s_cnt_sample,
                                            s_sum_sample,
                                            s_avg_sample,
                                            s_var_sample,
                                            s_cnt_col,
                                            s_sum_col,
                                            s_avg_col,
                                            s_var_col,
                                            s_cnt_col_sample,
                                            s_sum_col_sample,
                                            s_avg_col_sample,
                                            s_var_col_sample);
}


TCErrorCode stats_infer_anova_two_way_rep_compute_d_e_dist(const TCDistArray*   data,
    TCUInt64  cnt_row_sample,
    TCDouble  alpha,
    TCDouble* f_sample,
    TCDouble* f_col,
    TCDouble* f_int,
    TCDouble* p_sample,
    TCDouble* p_col,
    TCDouble* p_int,
    TCDouble* f_crit_sample,
    TCDouble* f_crit_col,
    TCDouble* f_crit_int,
    TCDouble* ss_sample,
    TCDouble* ss_col,
    TCDouble* ss_int,
    TCDouble* ss_err,
    TCDouble* ss_tot,
    TCUInt64* df_sample,
    TCUInt64* df_col,
    TCUInt64* df_int,
    TCUInt64* df_err,
    TCUInt64* df_tot,
    TCDouble* ms_sample,
    TCDouble* ms_col,
    TCDouble* ms_int,
    TCDouble* ms_err,
    TCDistArray* s_cnt_sample,
    TCDistArray* s_sum_sample,
    TCDistArray* s_avg_sample,
    TCDistArray* s_var_sample,
    TCDistArray* s_cnt_col,
    TCDistArray* s_sum_col,
    TCDistArray* s_avg_col,
    TCDistArray* s_var_col,
    TCDistArray* s_cnt_col_sample,
    TCDistArray* s_sum_col_sample,
    TCDistArray* s_avg_col_sample,
    TCDistArray* s_var_col_sample)
{
    return stats_infer_anova_tworep_dist<TCDouble>(data, cnt_row_sample, alpha,
                                            f_sample, f_col, f_int,
                                            p_sample, p_col, p_int,
                                            f_crit_sample, f_crit_col, f_crit_int,
                                            ss_sample, ss_col, ss_int, ss_err, ss_tot,
                                            df_sample, df_col, df_int, df_err, df_tot,
                                            ms_sample, ms_col, ms_int, ms_err,
                                            s_cnt_sample,
                                            s_sum_sample,
                                            s_avg_sample,
                                            s_var_sample,
                                            s_cnt_col,
                                            s_sum_col,
                                            s_avg_col,
                                            s_var_col,
                                            s_cnt_col_sample,
                                            s_sum_col_sample,
                                            s_avg_col_sample,
                                            s_var_col_sample);
}
