#<copyright>
# Copyright (c) Microsoft Corporation.  All rights reserved.
#</copyright>

!include "..\..\..\..\Build\make.targets"

$(INT_DIR)\anova_single.obj: ..\Descriptive\anova_single.h
$(INT_DIR)\anova_two.obj: ..\Descriptive\anova_two.h
$(INT_DIR)\anova_tworep.obj: ..\Descriptive\anova_tworep.h
$(INT_DIR)\avedev.obj: ..\Descriptive\avedev.h
$(INT_DIR)\average.obj: ..\Descriptive\average.h
$(INT_DIR)\range.obj: ..\Descriptive\range.h
$(INT_DIR)\skew.obj: ..\Descriptive\skew.h
$(INT_DIR)\skew.obj: ..\Descriptive\kurt.h
$(INT_DIR)\devsq.obj: ..\Descriptive\devsq.h
$(INT_DIR)\bernoulli.obj: ..\dist\bernoulli.h
$(INT_DIR)\binom.obj: ..\dist\binom.h
$(INT_DIR)\chisq.obj: ..\dist\chisq.h
$(INT_DIR)\cov.obj: ..\Descriptive\cov.h
$(INT_DIR)\covp.obj: ..\Descriptive\cov.h
$(INT_DIR)\moment.obj: ..\Descriptive\moment.h
$(INT_DIR)\moment_central.obj: ..\Descriptive\moment_central.h
$(INT_DIR)\pearson.obj: ..\Descriptive\pearson.h
$(INT_DIR)\ks_test.obj: ..\Inference\ks_test.h ..\Inference\ks_dist.h
$(INT_DIR)\ks2_test.obj: ..\Inference\ks2_test.h ..\Inference\ks2_dist.h
$(INT_DIR)\logistic.obj: ..\dist\logistic.h
$(INT_DIR)\lognorm.obj: ..\dist\lognorm.h
$(INT_DIR)\rayleigh.obj: ..\dist\rayleigh.h
$(INT_DIR)\beta.obj: ..\dist\beta.h
$(INT_DIR)\fisher.obj: ..\dist\fisher.h
$(INT_DIR)\fisher_test.obj: ..\dist\hypgeom.h
$(INT_DIR)\forecast.obj: ..\Regression\forecast.h
$(INT_DIR)\gamma.obj: ..\dist\gamma.h
$(INT_DIR)\geometric.obj: ..\dist\geometric.h
$(INT_DIR)\gev.obj: ..\dist\gev.h
$(INT_DIR)\gumbel.obj: ..\dist\gumbel.h
$(INT_DIR)\hypgeom.obj: ..\dist\hypgeom.h
$(INT_DIR)\intercept.obj: ..\Regression\intercept.h
$(INT_DIR)\negbinom.obj: ..\dist\negbinom.h
$(INT_DIR)\norm.obj: ..\dist\norm.h
$(INT_DIR)\regressionOperators.obj: ..\Regression\regressionOperators.h
$(INT_DIR)\weibull.obj: ..\dist\weibull.h
$(INT_DIR)\expon.obj: ..\dist\expon.h
$(INT_DIR)\f.obj: ..\dist\f.h
$(INT_DIR)\poisson.obj: ..\dist\poisson.h
$(INT_DIR)\cauchy.obj: ..\dist\cauchy.h
$(INT_DIR)\laplace.obj: ..\dist\laplace.h
$(INT_DIR)\norm_s.obj: ..\dist\norm_s.h
$(INT_DIR)\pareto.obj: ..\dist\pareto.h
$(INT_DIR)\rand_perm.obj: ..\Utilities\rand_perm.h
$(INT_DIR)\rank_eq.obj: ..\Descriptive\rank_eq.h
$(INT_DIR)\rank_avg.obj: ..\Descriptive\rank_avg.h
$(INT_DIR)\t.obj: ..\dist\t.h
$(INT_DIR)\t_test.obj: ..\Inference\t_test.h
$(INT_DIR)\chisq_test.obj: ..\Inference\chisq_test.h
$(INT_DIR)\slope.obj: ..\Regression\slope.h
$(INT_DIR)\steyx.obj: ..\Regression\steyx.h
$(INT_DIR)\stdev_p.obj: ..\Descriptive\stdev_p.h
$(INT_DIR)\stdev_s.obj: ..\Descriptive\stdev_s.h
$(INT_DIR)\uniform.obj: ..\dist\uniform.h
$(INT_DIR)\var_p.obj: ..\Descriptive\var_p.h
$(INT_DIR)\var_s.obj: ..\Descriptive\var_s.h
$(INT_DIR)\esd.obj: ..\Outliers\esd.h
$(INT_DIR)\mw_test.obj: ..\Inference\mw_test.h
$(INT_DIR)\wsr_test.obj: ..\Inference\wsr_test.h
$(INT_DIR)\z_test.obj: ..\Inference\z_test.h
$(INT_DIR)\median.obj: ..\Descriptive\median.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\median_dev.obj: ..\Descriptive\median.h ..\Descriptive\median_dev.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\interquartile_dist.obj: ..\Descriptive\interquartile_dist.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\large.obj: ..\Descriptive\large.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\small.obj: ..\Descriptive\small.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\quantile_exc.obj: ..\Descriptive\quantile_exc.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\quantile_inc.obj: ..\Descriptive\quantile_inc.h ..\Descriptive\qselect.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\percentrank_exc.obj: ..\Descriptive\percentrank_exc.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\percentrank_inc.obj: ..\Descriptive\percentrank_inc.h ..\Descriptive\qselect_utils.h
$(INT_DIR)\crosstabulate_numbers.obj: ..\Descriptive\crosstabulate_numbers.h
$(INT_DIR)\imputation_mean.obj: ..\Imputation\imputation_mean.h
$(INT_DIR)\lvcf.obj: ..\Imputation\lvcf.h
$(INT_DIR)\dq_test.obj: ..\Outliers\dq_test.h ..\Outliers\dq_test_method.h
$(INT_DIR)\moving_average_simple.obj: ..\Smoothing\moving_average_simple.h ..\Smoothing\moving_average.h
$(INT_DIR)\moving_average_weighted.obj: ..\Smoothing\moving_average_weighted.h ..\Smoothing\moving_average.h
$(INT_DIR)\moving_average_triangular.obj: ..\Smoothing\moving_average_triangular.h ..\Smoothing\moving_average.h
$(INT_DIR)\moving_average_cumulative.obj: ..\Smoothing\moving_average_cumulative.h ..\Smoothing\moving_average.h
$(INT_DIR)\moving_average_exponential.obj: ..\Smoothing\moving_average_exponential.h ..\Smoothing\moving_average.h
$(INT_DIR)\adf_test.obj: ..\TimeSeries\adf_test.h ..\TimeSeries\TimeSeriesUtils.h ..\TimeSeries\TimeSeriesUtilsLA.h ..\TimeSeries\TimeSeriesUtilsOptimization.h
$(INT_DIR)\uniform_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\norm_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\norm_s_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\expon_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\binom_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\negbinom_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\bernoulli_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\chisq_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\beta_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\gamma_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\discruni_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\lognorm_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\weibull_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\rayleigh_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\cauchy_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\poisson_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\geometric_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\hypgeom_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\f_rand.obj: ..\dist\TCRNGUtils.h
$(INT_DIR)\norm_fit.obj: ..\MLE\norm_fit.h
$(INT_DIR)\binom_fit.obj: ..\MLE\binom_fit.h
$(INT_DIR)\poisson_fit.obj: ..\MLE\poisson_fit.h
$(INT_DIR)\expon_fit.obj: ..\MLE\expon_fit.h
$(INT_DIR)\timeseries_ar.obj: ..\TimeSeries\timeseries_ar.h ..\TimeSeries\TimeSeriesUtils.h ..\TimeSeries\TimeSeriesUtilsLA.h ..\TimeSeries\TimeSeriesUtilsOptimization.h

{..\Descriptive}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Descriptive}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Descriptive}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Descriptive}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Imputation}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Imputation}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Imputation}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Imputation}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Inference}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Inference}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Inference}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Inference}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Outliers}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Outliers}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Outliers}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Outliers}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<
 
{..\dist}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\dist}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\dist}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\dist}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\DataProcessing}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\DataProcessing}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\DataProcessing}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\DataProcessing}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Regression}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Regression}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Regression}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Regression}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Smoothing}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Smoothing}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Smoothing}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Smoothing}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\MLE}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\MLE}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\MLE}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\MLE}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\TimeSeries}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\TimeSeries}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\TimeSeries}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\TimeSeries}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<

{..\Utilities}.c{$(INT_DIR)}.obj:
	$(ICL) /c $(C99FLAGS) /Fo$@ $<

{..\Utilities}.cpp{$(INT_DIR)}.obj:
	$(ICL) /c $(CPPFLAGS) /Fo$@ $<

{..\Utilities}.c{}.i:
	$(ICL) /P $(C99FLAGS) /Fo$@ $<

{..\Utilities}.cpp{}.i:
	$(ICL) /P $(CPPFLAGS) /Fo$@ $<
